version: "3"

services:
  fronend:
    build:
      context: .
      dockerfile: Dockerfile                     
    image: ${DOCKER_IMAGE_NAME:-alifronrfndimage}:${TAG:-latest}
    container_name: ${DOCKER_CONTAINER_NAME:-aliFronrEndContainer}
    ports:
      - ${APP_PORT:-3000}:3000    
    restart: unless-stopped

